name: cwpk-environment
channels:
  - conda-forge
dependencies:
  - bokeh
  - ftfy
  - holoviews
  - ipywidgets
  - networkx
  - owlready2
  - pandoc
  - panel
  - pip
  - pytest
  - python
  - rdflib
  - sparqlwrapper
  - pip:
    - beautifulsoup4
    - cowpoke
    - matplotlib
    - pandas
    - pyviz
