name: cwpk-environment
channels:
  - conda-forge
dependencies:
  - bokeh
  - ftfy
  - holoviews
  - networkx
  - numpy
  - owlready2
  - pandoc
  - panel
  - pip
  - pytest
  - python
  - rdflib
  - sparqlwrapper
  - pip:
    - beautifulsoup4
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - pyviz
    - matplotlib
