name: cwpk-environment
channels:
  - conda-forge
dependencies:
  - ftfy
  - networkx
  - owlready2
  - pandoc
  - pip
  - pytest
  - python
  - rdflib
  - sparqlwrapper
  - pip:
    - beautifulsoup4
    - cowpoke
    - matplotlib
    - pandas
